export const SIGNUP_STARTED = "SIGNUP_STARTED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const LOGOUT = "LOGOUT";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";

export const FETCH_ZEAL_ID_STARTED = "FETCH_ZEAL_ID_STARTED";
export const FETCH_ZEAL_ID_SUCCESS = "GET_ZEAL_ID_SUCCESS";
export const FETCH_ZEAL_ID_FAILURE = "GET_ZEAL_ID_FAILURE";
export const FETCH_ZEAL_ID_END = "FETCH_ZEAL_ID_END";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";
